# Generated by Django 4.2.7 on 2025-03-10 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade_id', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('buyer_order_id', models.BigIntegerField(blank=True, null=True)),
                ('seller_order_id', models.BigIntegerField(blank=True, null=True)),
                ('is_buyer_maker', models.BooleanField(default=False)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_updates', to='crypto_stream.cryptopair')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pair', 'timestamp'], name='crypto_stre_pair_id_5b6a6f_idx'), models.Index(fields=['timestamp'], name='crypto_stre_timesta_d5a788_idx')],
            },
        ),
    ]
